Fix pre-commit/build errors
At the moment any pre-commit/build fails due to the following errors:

1.

    CSRF_TRUSTED_ORIGINS = [f"https://{os.environ['DOMAIN_NAME']}"]
                                       ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'DOMAIN_NAME'

2.

ModuleNotFoundError: No module named 'clamd'

3.

ModuleNotFoundError: No module named 'notifications_python_client'

These changes are to fix those errors